export const projects = [
  {
    title: "Neka Sport",
    description: "",
    image: "/images/2.png",
    tags: ["Sanity", "Next", "Tailwind"],
    source: "https://github.com/Tansi-Jones/Neka-Sports",
    visit: "https://neka-sports.vercel.app/",
    id: 0,
  },
  {
    title: "Airbnb Clone",
    description: "",
    image: "/images/3.png",
    tags: ["Next", "Tailwind"],
    source: "https://airbnbclone-chi.vercel.app/",
    visit: "https://airbnbclone-chi.vercel.app/",
    id: 1,
  },
  {
    title: "The Weather",
    description: "",
    image: "/images/4.png",
    tags: ["Next", "Tailwind"],
    source: "https://github.com/Tansi-Jones/Weather-App",
    visit: "https://the-weather-gold.vercel.app/",
    id: 2,
  },
  {
    title: "Apartmen",
    description: "",
    image: "/images/5.png",
    tags: ["Next", "Tailwind"],
    source: "https://github.com/Tansi-Jones/Apartmen",
    visit: "https://apartmen.vercel.app/",
    id: 3,
  },
  {
    title: "Portfolio",
    description: "",
    image: "/images/6.png",
    tags: ["Next", "Tailwind"],
    source: "https://github.com/AlphonseBrandon/Alphonse-Portfolio",
    visit: "https://alphonse.vercel.app/",
    id: 4,
  },
  {
    title: "ForosPay",
    description: "",
    image: "/images/7.png",
    tags: ["Figma"],
    source: "https://dribbble.com/shots/18120407-Foros-Pay",
    id: 5,
  },
  {
    title: "Very Best",
    description: "",
    image: "/images/1.png",
    tags: ["Next", "Tailwind", "MongoDB"],
    source: "https://github.com/Tansi-Jones/Very-Best",
    visit: "https://very-best.vercel.app/",
    id: 6,
  },
  {
    title: "Women Lift",
    description: "",
    image: "/images/8.png",
    tags: ["Figma"],
    source: "https://dribbble.com/shots/18120476-Women-Lift",
    id: 7,
  },
];

export const TimeLineData = [
  { year: 2015, text: "Started my journey" },
  { year: 2017, text: "Worked as a freelance developer" },
  { year: 2021, text: "Joined Neotecc LLC" },
  { year: 2022, text: "Working as a freelance developer" },
  { year: 2022, text: "Joined LINK.IO" },
];
