export const projects = [
  {
    title: "Neka Sport",
    description: "",
    image: "/images/2.png",
    tags: ["Sanity", "Next", "Tailwind"],
    source: "https://google.com",
    visit: "https://google.com",
    id: 0,
  },
  {
    title: "Airbnb Clone",
    description: "",
    image: "/images/3.png",
    tags: ["Next", "Tailwind"],
    source: "https://google.com",
    visit: "https://google.com",
    id: 4,
  },
  {
    title: "The Weather",
    description: "",
    image: "/images/4.png",
    tags: ["Next", "Tailwind"],
    source: "https://google.com",
    visit: "https://google.com",
    id: 5,
  },
  {
    title: "Apartmen",
    description: "",
    image: "/images/5.png",
    tags: ["Next", "Tailwind"],
    source: "https://google.com",
    visit: "https://google.com",
    id: 6,
  },
  {
    title: "Portfolio",
    description: "",
    image: "/images/6.png",
    tags: ["React", "ChatEngine", "Firebase"],
    source: "https://google.com",
    visit: "https://google.com",
    id: 6,
  },
  {
    title: "Very Best",
    description: "",
    image: "/images/1.png",
    tags: ["Next", "Tailwind", "MongoDB"],
    source: "https://google.com",
    // visit: "https://google.com",
    id: 3,
  },
];

export const TimeLineData = [
  { year: 2015, text: "Started my journey" },
  { year: 2017, text: "Worked as a freelance developer" },
  { year: 2021, text: "Joined Neotecc LLC" },
  { year: 2022, text: "Working as a freelance developer" },
  { year: 2022, text: "Joined LINK.IO" },
];
